spring:
#  config:
#    import: optional:configserver:http://localhost:8080/
  data:
    mongodb:
      uri: "mongodb+srv://subu-user:12345%40Dev@cluster0.5frxr.mongodb.net/cluster0?retryWrites=true&w=majority&maxIdleTimeMS=300000"

server:
  port: 8000

logging:
  level:
    org:
      springframework:
        data: DEBUG
        
sentry:
  dsn: https://5b42067405f84eb59683baa45faff0f6@o1126539.ingest.sentry.io/6167465
  # Set traces-sample-rate to 1.0 to capture 100% of transactions for performance monitoring.
  # We recommend adjusting this value in production.
  traces-sample-rate: 1.0
