spring:
#  config:
#    import: optional:configserver:http://localhost:8080/
  data:
    mongodb:
      uri: "mongodb+srv://subu-user:12345%40Dev@cluster0.5frxr.mongodb.net/cluster0?retryWrites=true&w=majority"

server:
  port: 8000

logging:
  level:
    org:
      springframework:
        data: DEBUG