spring:
  config:
    import: optional:configserver:http://localhost:8080/
  data:
    mongodb:
      uri="mongodb://localhost:27017"
    database: clinic21st

server:
  port: 8000

logging:
  level:
    org:
      springframework:
        data: DEBUG